### ISSUE TITLE
L1 Bridge does not work with SCWs

### ISSUE THREAD

**Issue by derekchiang** [lidofinance/lido-l2#49] opened 2023-08-03 02:29 UTC
The L1 ERC20 token bridge reverts if the sender is an SCW: https://github.com/lidofinance/lido-l2/blob/471993c23f3f8c378b9ef4598e703381e9462189/contracts/optimism/L1ERC20TokenBridge.sol#L58-L60

**Comment by zdenham** [comment] 2023-08-03 02:36
This is an issue as AA wallets are increasingly adopted

**Comment by TheDZhon** [comment] 2023-08-09 08:55
Hey, thank you for raising this :+1: 

The issue is totally valid and somewhat relevant to #46 

Will be looking to plan it for the next upgrade :pray:

**Comment by TheDZhon** [comment] 2023-08-09 14:46
Worth noting: https://community.optimism.io/docs/developers/bridge/standard-bridge/#deposits
tl;dr: there is a known limitation even for standard optimism bridge for SCW

**Comment by TheDZhon** [comment] 2023-08-09 14:57
**UPDATE**

You can use [depositTo](https://github.com/lidofinance/lido-l2/blob/471993c23f3f8c378b9ef4598e703381e9462189/contracts/optimism/L1ERC20TokenBridge.sol#L65) if you know what are you doing for sure

![image](https://github.com/lidofinance/lido-l2/assets/961317/2655de6d-8d0e-4122-a696-931db1912190)

If you use the same sender and destination addresses (like `deposit` does), you might send funds to the wrong address in general (suppose your SCW isn't represented with the same address on L1 and L2).

**Comment by TheDZhon** [comment] 2023-11-10 10:16
Closing the issue as being relevant to the design decisions of Opti stack towards having a dedicated `depositTo` method for SCW

**Closed by TheDZhon** 2023-11-10 10:16 UTC
